debug: true


spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: sys as sysdba
    password: admin@123
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 7001